export default {
	down: 'ms-Icon ms-Icon--ChevronDown',
	up: 'ms-Icon ms-Icon--ChevronUp',
	right: 'ms-Icon ms-Icon--ChevronRight',
	doubleDown: 'ms-Icon ms-Icon--DoubleChevronDown',
	doubleUp: 'ms-Icon ms-Icon--DoubleChevronUp',
	prev: 'ms-Icon ms-Icon--Up',
	next: 'ms-Icon ms-Icon--Down',
	checkMark: 'ms-Icon ms-Icon--CheckMark',
	calendarWeek: 'ms-Icon ms-Icon--CalendarWeek',
	clear: 'ms-Icon ms-Icon--Clear',
	search: 'ms-Icon ms-Icon--Search',
	info: 'ms-Icon ms-Icon--Info',
	cancel: 'ms-Icon ms-Icon--Cancel',
	circleRing: 'ms-Icon ms-Icon--CircleRing',
	statusCircleCheckmark: 'ms-Icon ms-Icon--StatusCircleCheckmark',
	star: 'ms-Icon ms-Icon--FavoriteStar',
	starFilled: 'ms-Icon ms-Icon--FavoriteStarFill'
}